name: Renku Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        RENKU_VERSION: ["", "0.8.2", "0.9.1"]
        EXTENSIONS: ["py3.7", "r3.6.1", "bioc3_10", "cuda9.2", "cuda10.0-tf1.14"]

    steps:

    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: actions/checkout@v2
    - name: Build renku project docker images
      run: |
        if [[ ${{ github.ref }} == refs/tags* ]]; then
          export LABEL=$(echo ${{ github.ref }} | cut -d / -f 3)
        else
          export LABEL=$(echo ${{ github.sha }} | cut -c 1-7)
        fi
        export DOCKER_TAG="renku$RENKU_VERSION-$EXTENSION-$LABEL"

        if [ -z $RENKU_VERSION ]; then
          export RENKU_PIP_SPEC=renku
        else
          export RENKU_PIP_SPEC="renku==${RENKU_VERSION}"
        fi
        docker build docker/$EXTENSION --build-arg RENKU_PIP_SPEC=${RENKU_PIP_SPEC} --tag $DOCKER_NAME:$DOCKER_TAG
        docker push $DOCKER_NAME:$DOCKER_TAG
      env:
        EXTENSION: ${{ matrix.EXTENSIONS }}
        RENKU_VERSION: ${{ matrix.RENKU_VERSION }}
        DOCKER_NAME: "alexisrapintest/renku-docker-test"
